export type AudiobookBase = {
	authors: ;
	available_markets: ;
	copyrights: ;
	description: string;
	html_description: string;
	edition?: string;
	explicit: boolean;
	external_urls: ;
	href: string;
	id: string;
	images: ;
	languages: ;
	media_type: string;
	name: string;
	narrators: ;
	publisher: string;
	type: string;
	uri: string;
	total_chapters: number;
};